# Automatically triggered when a new tag like coldstart-nodejs-100 is pushed to
# the source repository.
steps:

# Build the docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'VERSION=$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/coldstart-nodejs:$TAG_NAME', '.']

images: ['gcr.io/$PROJECT_ID/coldstart-nodejs:$TAG_NAME']